Remove sudo requirement from updater script

diff --git a/scripts/updater b/scripts/updater
--- a/scripts/updater
+++ b/scripts/updater
@@ -27,7 +27,7 @@ cfg_haskey $configfile version || exists=false
 if [ "$exists" == false ]; then
     if [ -f $configfile ]; then
         value=$(cat $configfile)
-        sudo rm $configfile
+        rm $configfile
     fi  
     echo "" > $configfile
     cfg_write $configfile version 1
@@ -113,7 +113,7 @@ function performupdate() {
     # Update cathook
     cd build && cmake .. && cmake --build . --target cathook -- -j$proccount || { echo -e "\033[1;31m \n \nFailed to compile cathook\n\033[0m"; exit 1; }
     # Update data
-    sudo cmake --build . --target data || { echo -e "\033[1;31m\nFailed to update /opt/cathook/data directory\n\033[0m"; exit 1; }
+    cmake --build . --target data || { echo -e "\033[1;31m\nFailed to update /opt/cathook/data directory\n\033[0m"; exit 1; }
     echo -e "\n\033[1;34mCathook updated successfully\n\033[0m"
     rm -f ${LOCKFILE}
 }
